// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd7QcgeNx05eA1To71cuq3K28JpzPbTCo',
    appId: '1:19229854510:web:d6e6135a3ca3cb734e48bf',
    messagingSenderId: '19229854510',
    projectId: 'icd-alar',
    authDomain: 'icd-alar.firebaseapp.com',
    storageBucket: 'icd-alar.firebasestorage.app',
    measurementId: 'G-LXHTL6PPBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbi-4_Ipwm0ALLzKK6TLpSCESjFp4HckI',
    appId: '1:19229854510:android:ee389bf28dc828194e48bf',
    messagingSenderId: '19229854510',
    projectId: 'icd-alar',
    storageBucket: 'icd-alar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQvetb731nilu32WrWSHJeLvcSYAxlLmM',
    appId: '1:19229854510:ios:3274e2380d0814294e48bf',
    messagingSenderId: '19229854510',
    projectId: 'icd-alar',
    storageBucket: 'icd-alar.firebasestorage.app',
    iosClientId: '19229854510-2gb86o7ik82d8d9tn901u820m8qqc6r4.apps.googleusercontent.com',
    iosBundleId: 'com.example.icd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQvetb731nilu32WrWSHJeLvcSYAxlLmM',
    appId: '1:19229854510:ios:3274e2380d0814294e48bf',
    messagingSenderId: '19229854510',
    projectId: 'icd-alar',
    storageBucket: 'icd-alar.firebasestorage.app',
    iosClientId: '19229854510-2gb86o7ik82d8d9tn901u820m8qqc6r4.apps.googleusercontent.com',
    iosBundleId: 'com.example.icd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd7QcgeNx05eA1To71cuq3K28JpzPbTCo',
    appId: '1:19229854510:web:490abbb8bf536e214e48bf',
    messagingSenderId: '19229854510',
    projectId: 'icd-alar',
    authDomain: 'icd-alar.firebaseapp.com',
    storageBucket: 'icd-alar.firebasestorage.app',
    measurementId: 'G-6SWEN8XTV3',
  );

}